//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как О квестах.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавить комментарий.
        /// </summary>
        internal static string AddFeedbackMessage {
            get {
                return ResourceManager.GetString("AddFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бронирование on-line.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Указанные дата и время уже заняты.
        /// </summary>
        internal static string BookingBookedMessage {
            get {
                return ResourceManager.GetString("BookingBookedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бронирование не выполнено.
        /// </summary>
        internal static string BookingBookedTitle {
            get {
                return ResourceManager.GetString("BookingBookedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вам на почту отправлено письмо с полной информацией по Вашему бронированию.
        /// </summary>
        internal static string BookingCompleteMessage {
            get {
                return ResourceManager.GetString("BookingCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бронирование выполнено.
        /// </summary>
        internal static string BookingCompleteTitle {
            get {
                return ResourceManager.GetString("BookingCompleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Указанные дата и время недопустимы.
        /// </summary>
        internal static string BookingFailureMessage {
            get {
                return ResourceManager.GetString("BookingFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бронирование невозможно.
        /// </summary>
        internal static string BookingFailureTitle {
            get {
                return ResourceManager.GetString("BookingFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бронирование на.
        /// </summary>
        internal static string BookingOn {
            get {
                return ResourceManager.GetString("BookingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подарочные сертификаты.
        /// </summary>
        internal static string Certs {
            get {
                return ResourceManager.GetString("Certs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Закрыть.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарии.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарии к квесту.
        /// </summary>
        internal static string CommentsForQuest {
            get {
                return ResourceManager.GetString("CommentsForQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сложность.
        /// </summary>
        internal static string Complexity {
            get {
                return ResourceManager.GetString("Complexity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подтверждение бронирования.
        /// </summary>
        internal static string ConfirmBooking {
            get {
                return ResourceManager.GetString("ConfirmBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Контакты.
        /// </summary>
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Стоимость.
        /// </summary>
        internal static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата и время.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Описание.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Подробнее.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Продолжительность.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарии.
        /// </summary>
        internal static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отзыв могут оставить только пользователи, учавствовавшие в игре. По вашему почтовому адресу не найдена подтвержденная бронь.
        /// </summary>
        internal static string FeedbackMessageFailureMessage {
            get {
                return ResourceManager.GetString("FeedbackMessageFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Невозможно оставить отзыв.
        /// </summary>
        internal static string FeedbackMessageFailureTitle {
            get {
                return ResourceManager.GetString("FeedbackMessageFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Добавление отзыва.
        /// </summary>
        internal static string FeedbackMessageForm {
            get {
                return ResourceManager.GetString("FeedbackMessageForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отзыв успешно отправлен.
        /// </summary>
        internal static string FeedbackMessageSuccessTitle {
            get {
                return ResourceManager.GetString("FeedbackMessageSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Ваш отзыв успешно отправлен и будет опубликован после модерации.
        /// </summary>
        internal static string FeedbackMessagSuccessMessage {
            get {
                return ResourceManager.GetString("FeedbackMessagSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Текст отзыва.
        /// </summary>
        internal static string FeedbackText {
            get {
                return ResourceManager.GetString("FeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Все права защищены.
        /// </summary>
        internal static string Footer {
            get {
                return ResourceManager.GetString("Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Вернуться к бронированию.
        /// </summary>
        internal static string GotoBooking {
            get {
                return ResourceManager.GetString("GotoBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Информация.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Войти.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Неверное имя пользователя или пароль.
        /// </summary>
        internal static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Авторизация.
        /// </summary>
        internal static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как мин..
        /// </summary>
        internal static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарий.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Пароль.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как чел..
        /// </summary>
        internal static string Pers {
            get {
                return ResourceManager.GetString("Pers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Количество.
        /// </summary>
        internal static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите адрес электронной почты.
        /// </summary>
        internal static string PhEmail {
            get {
                return ResourceManager.GetString("PhEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите отзыв.
        /// </summary>
        internal static string PhFeedbackText {
            get {
                return ResourceManager.GetString("PhFeedbackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите имя.
        /// </summary>
        internal static string PhName {
            get {
                return ResourceManager.GetString("PhName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Комментарий (необязательно).
        /// </summary>
        internal static string PhNote {
            get {
                return ResourceManager.GetString("PhNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Телефон.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 911-5555555.
        /// </summary>
        internal static string PhoneNmb {
            get {
                return ResourceManager.GetString("PhoneNmb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите номер телефона.
        /// </summary>
        internal static string PhPhone {
            get {
                return ResourceManager.GetString("PhPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Количество игроков.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Стоимость, руб..
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Квест.
        /// </summary>
        internal static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Бронирование квеста.
        /// </summary>
        internal static string QuestBooking {
            get {
                return ResourceManager.GetString("QuestBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Квесты.
        /// </summary>
        internal static string Quests {
            get {
                return ResourceManager.GetString("Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как руб..
        /// </summary>
        internal static string Rub {
            get {
                return ResourceManager.GetString("Rub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выберите дату:.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Забронировать.
        /// </summary>
        internal static string SendBooking {
            get {
                return ResourceManager.GetString("SendBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Отправить отзыв.
        /// </summary>
        internal static string SendFeedbackMessage {
            get {
                return ResourceManager.GetString("SendFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Расписание.
        /// </summary>
        internal static string Shedule {
            get {
                return ResourceManager.GetString("Shedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ул. Смолячкова 14 корпус 4.
        /// </summary>
        internal static string ShortAddress {
            get {
                return ResourceManager.GetString("ShortAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Выберите время.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Имя пользователя.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Веб-сайт.
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как сб.-вс..
        /// </summary>
        internal static string Weekends {
            get {
                return ResourceManager.GetString("Weekends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как пн.-пт. до 17:00.
        /// </summary>
        internal static string WorkdaysDay {
            get {
                return ResourceManager.GetString("WorkdaysDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как пн.-пт. после 17:00.
        /// </summary>
        internal static string WorkdaysEvening {
            get {
                return ResourceManager.GetString("WorkdaysEvening", resourceCulture);
            }
        }
    }
}
